prep_pipe:
  class_proportion: 0.01149217306656834
  feat_dim:
  - 5703447
  - 77
  var_names:
  - CLUSTER
  - CICLO_DE_VIDA
  - PRINCIPALIDADE
  - LOYALTY_LVL
  - FLAG_DATA_OUT
  - FLAG_CARTAO_CREDITO
  - SALDO_EM_CONTA30
  - SALDO_EM_CONTA60
  - SALDO_EM_CONTA90
  - TPN_SELLER30
  - TPN_FUNDER30
  - TPN_RECIEVER30
  - TPN_BORROWER30
  - TPN_COMPRAS_WEB30
  - TPN_COMPRAS_APP30
  - TPN_PRODUTOS_BANCARIOS30
  - TPN_TRANSFERENCIAS_DIFFTIT30
  - TPN_TRANSFERENCIAS_MSMTIT30
  - TPN_SAQUES30
  - TPN_SELLER60
  - TPN_FUNDER60
  - TPN_RECIEVER60
  - TPN_BORROWER60
  - TPN_COMPRAS_WEB60
  - TPN_COMPRAS_APP60
  - TPN_PRODUTOS_BANCARIOS60
  - TPN_TRANSFERENCIAS_DIFFTIT60
  - TPN_TRANSFERENCIAS_MSMTIT60
  - TPN_SAQUES60
  - TPN_SELLER90
  - TPN_FUNDER90
  - TPN_RECIEVER90
  - TPN_BORROWER90
  - TPN_COMPRAS_WEB90
  - TPN_COMPRAS_APP90
  - TPN_PRODUTOS_BANCARIOS90
  - TPN_TRANSFERENCIAS_DIFFTIT90
  - TPN_TRANSFERENCIAS_MSMTIT90
  - TPN_SAQUES90
  - TPV_SELLER30
  - TPV_FUNDER30
  - TPV_RECIEVER30
  - TPV_BORROWER30
  - TPV_COMPRAS_WEB30
  - TPV_COMPRAS_APP30
  - TPV_PRODUTOS_BANCARIOS30
  - TPV_TRANSFERENCIAS_DIFFTIT30
  - TPV_TRANSFERENCIAS_MSMTIT30
  - TPV_SAQUES30
  - TPV_SELLER60
  - TPV_FUNDER60
  - TPV_RECIEVER60
  - TPV_BORROWER60
  - TPV_COMPRAS_WEB60
  - TPV_COMPRAS_APP60
  - TPV_PRODUTOS_BANCARIOS60
  - TPV_TRANSFERENCIAS_DIFFTIT60
  - TPV_TRANSFERENCIAS_MSMTIT60
  - TPV_SAQUES60
  - TPV_SELLER90
  - TPV_FUNDER90
  - TPV_RECIEVER90
  - TPV_BORROWER90
  - TPV_COMPRAS_WEB90
  - TPV_COMPRAS_APP90
  - TPV_PRODUTOS_BANCARIOS90
  - TPV_TRANSFERENCIAS_DIFFTIT90
  - TPV_TRANSFERENCIAS_MSMTIT90
  - TPV_SAQUES90
  - SHOWNS_OPF
  - OPENS_OPF
  - SHOWNS_30
  - OPENS_30
  - SHOWNS_60
  - OPENS_60
  - SHOWNS_90
  - OPENS_90
train_pipe:
  class_proportion: 0.01149217306656834
  feat_dim:
  - 5703447
  - 77
