train:
  package: lightgbm
  module: LGBMClassifier
  params:
    boosting_type: gbdt
    n_estimators: 200
    max_depth: 5
    n_jobs: 20
    is_unbalance: "true"
test_sample_rate: 0.20
tuning:
  n_trials: 10
  direction: maximize 
  pred_tuning: predict_proba
  sample_rate: 0.20
  tuning_metric:
    package: sklearn.metrics
    module: roc_auc_score
  random_state: 42
  n_estimators: 200
  device: cpu
  trial.suggest_loguniform:
    colsample_bytree: [0.2, 1.0]
    subsample: [0.4, 1.0]
    learning_rate: [0.01, 0.5]
  trial.suggest_categorical:
    max_depth: [3,4,5,6,7,8,9,10,11,12] 
calibration:
  method: sigmoid
  cv: prefit
  cal_sample_rate: 0.5
#optimize_threshold: True
report: True

